web:
  image: nginx:alpine
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    - ./conf/conf.d:/etc/nginx/conf.d:ro,Z
    - ./var:/usr/share/nginx/html:ro,Z
    - ./tmp/tmp:/tmp
    - ./tmp/log:/var/log/nginx
  ports:
    - "8080:80"
  restart: always
  container_name: web
